import RecoilRootWrapper from '@/utils/RecoilRootWrapper';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import RoundButton from '@/components/RoundButton/RoundButton';
import StyledComponentsRegistry from '@/assets/style';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	// 웹 이름
	title: 'Matdori',
	description: 'Generated by Matdori',
	viewport:
		'initial-scale=1.0,user-scalable=no,maximum-scale=1,width=device-width,minimum-scale=1,viewport-fit=cover',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body id='root' className={inter.className}>
				<RecoilRootWrapper>
					{/*스마트폰 전체 프레임 잡기*/}
					<div className='flex justify-center h-full'>
						{/*전체 크기 개발 이후에 변경 필요*/}
						<div className='relative inset-0 sm:w-[412px] w-full border border-gray overflow-y-scroll overflow-x-hidden scrollbar-hide'>
							<StyledComponentsRegistry>{children}</StyledComponentsRegistry>
						</div>
					</div>
				</RecoilRootWrapper>
			</body>
		</html>
	);
}
