import RecoilRootWrapper from '@/utils/RecoilRootWrapper';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	// 웹 이름
	title: 'Matdori',
	description: 'Generated by Matdori',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={inter.className}>

				<RecoilRootWrapper>
					{/*스마트폰 전체 프레임 잡기*/}
					<div className='flex justify-center'>
						{/*전체 크기 개발 이후에 변경 필요*/}
						<div className='md:w-[768px] w-full h-auto'>{children}</div>
					</div>
				</RecoilRootWrapper>
			</body>
		</html>
	);
}
